<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>IntelOrca.Biohazard.REEUtils</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
    <PackageReference Include="ModelContextProtocol" Version="1.3.0" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.49.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../IntelOrca.Biohazard.REE/IntelOrca.Biohazard.REE.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="data/**/*" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="GDeflate/runtimes/**/*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
