name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Setup .NET 10.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Restore
      run: dotnet restore
    - name: Build nupkg
      run: dotnet pack src/IntelOrca.Biohazard.REE -c Release -o .
    - name: Build reeutils
      run: |
        dotnet publish src/reeutils -c Release -o out/reeutils --os linux
        dotnet publish src/reeutils -c Release -o out/reeutils --os win
    - name: Run tests
      id: run_tests
      continue-on-error: true
      run: |
        dotnet test --no-build -c Release --logger "trx;LogFileName=test-results.trx" --logger "console;verbosity=detailed" --collect:"XPlat Code Coverage"
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          **/TestResults/
    - name: Publish test results
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        trx_files: '**/test-results.trx'
        check_run_annotations: 'all'
        compare_to_earlier_commit: false
    - name: Fail if tests failed
      if: steps.run_tests.outcome == 'failure'
      run: exit 1
    - name: Pack reeutils
      run: |
        cd out/reeutils
        rm -rf *.deps.json *.pdb de fr sv
        cp ../../script/* .
        cd ..
        tar czf ../reeutils.tar.gz .
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: reeutils
        path: |
          *.nupkg
          out/**/*
    - name: Create release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        fail_on_unmatched_files: true
        files: |
          *.nupkg
          reeutils.tar.gz
    - name: Publish to nuget.org
      if: startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget push *.nupkg --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json
